// import orcoos, { cast, STATES, setDriver, set, get, createConnection, connect, disconnect, startSession, pluralize, model, deleteModel, modelNames, plugin, connections, version, Orcoos, Schema, SchemaType, SchemaTypes, VirtualType, Types, Query, Model, Document, ObjectId, isValidObjectId, isObjectIdOrHexString, syncIndexes, Decimal128, Mixed, Date, Number, Error, now, CastError, SchemaTypeOptions, mongo, mquery, sanitizeFilter, trusted, skipMiddlewareFunction, overwriteMiddlewareResult } from './src/types/index';
import orcoos from './src/types/index';
export default orcoos;
// // Re-export for ESM support
// export const cast = cast;
// export const STATES = STATES;
// export const setDriver = setDriver;
// export const set = set;
// export const get = get;
export const createConnection = orcoos.createConnection;
export const connect = orcoos.connect;
export const disconnect = orcoos.disconnect;
// export const startSession = startSession;
// export const pluralize = pluralize;
export const model = orcoos.model;
// export const deleteModel = deleteModel;
// export const modelNames = modelNames;
// export const plugin = plugin;
// export const connections = connections;
export const version = orcoos.version;
export const Orcoos = orcoos.Orcoos;
export const Schema = orcoos.Schema;
// export const SchemaType = SchemaType;
// export const SchemaTypes = SchemaTypes;
// export const VirtualType = VirtualType;
// export const Types = Types;
// export const Query = Query;
export const Model = orcoos.Model;
export const Document = orcoos.Document;
export const ObjectId = orcoos.ObjectId;
// export const isValidObjectId = isValidObjectId;
// export const isObjectIdOrHexString = isObjectIdOrHexString;
// export const syncIndexes = syncIndexes;
export const Decimal128 = orcoos.Decimal128;
// export const Mixed = Mixed;
export const Date = orcoos.Date;
export const Number = orcoos.Number;
export const Error = orcoos.Error;
export const now = orcoos.now;
export const CastError = orcoos.CastError;
export const SchemaTypeOptions = orcoos.SchemaTypeOptions;
// export const mongo = mongo;
// export const mquery = mquery;
// export const sanitizeFilter = sanitizeFilter;
// export const trusted = trusted;
// export const skipMiddlewareFunction = skipMiddlewareFunction;
// export const overwriteMiddlewareResult = overwriteMiddlewareResult;

export const NoSQLConnectionString = orcoos.NoSQLConnectionString;